version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: concert_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - concert-net

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: user-service
    container_name: user-service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: concert_db
      DB_PORT: 3306
      USER_SERVICE_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - concert-net

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: booking-service
    container_name: booking-service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: concert_db
      DB_PORT: 3306
      BOOKING_SERVICE_PORT: 8001
    ports:
      - "8001:8001"
    depends_on:
      - mysql
    networks:
      - concert-net

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: payment-service
    container_name: payment-service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: concert_db
      DB_PORT: 3306
      PAYMENT_SERVICE_PORT: 8002
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    networks:
      - concert-net

volumes:
  mysql-data:

networks:
  concert-net:
    driver: bridge